package com.demo.models;
// Generated Aug 21, 2022, 12:19:02 AM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "booking", catalog = "book_table_online")
public class Booking implements java.io.Serializable {

	private Integer id;
	private Account account;
	private Restauranttable restauranttable;

	public Booking() {
	}

	public Booking(Account account, Restauranttable restauranttable) {
		this.account = account;
		this.restauranttable = restauranttable;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "accountid", nullable = false)
	public Account getAccount() {
		return this.account;
	}

	public void setAccount(Account account) {
		this.account = account;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tableid", nullable = false)
	public Restauranttable getRestauranttable() {
		return this.restauranttable;
	}

	public void setRestauranttable(Restauranttable restauranttable) {
		this.restauranttable = restauranttable;
	}

}
