package com.demo.models;
// Generated Aug 21, 2022, 12:19:02 AM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tabletype generated by hbm2java
 */
@Entity
@Table(name = "tabletype", catalog = "book_table_online")
public class Tabletype implements java.io.Serializable {

	private Integer id;
	private String name;
	private Set<Restauranttable> restauranttables = new HashSet<Restauranttable>(0);

	public Tabletype() {
	}

	public Tabletype(String name) {
		this.name = name;
	}

	public Tabletype(String name, Set<Restauranttable> restauranttables) {
		this.name = name;
		this.restauranttables = restauranttables;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 250)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tabletype")
	public Set<Restauranttable> getRestauranttables() {
		return this.restauranttables;
	}

	public void setRestauranttables(Set<Restauranttable> restauranttables) {
		this.restauranttables = restauranttables;
	}

}
